### PR TITLE
Revert "Rename vm_fault->virtual_address to vm_fault->address (for 4.…

### PR DESCRIPTION
**Pull request by duxing2007**

### CODE REVIEW

**Comment by davefellows** [comment]
Hey, I see you're reverting the change. Did this go to the wrong place? I had created a new branch origin/linux-4.10.y on my fork but looks like this went into origin/linux-4.9.y on your end.

**Comment by duxing2007** [comment]
Yes, I merge this commit into the wrong branch.
And I want to merge this commit into master branch.
It seems that no need to create 4.10 branch, since it's not a longterm stable branch.

**Comment by duxing2007** [comment]
Can you start a new pull request about this commit?
I will merge it into master.

**Comment by davefellows** [comment]
Done, but there are conflicts so might need to rethink. I based my 4.10 branch off 4.9. Would you advise that I pick up master instead? I had assumed the 4.9 branch was the most recent and therefore the closest to where I needed to be for 4.10.

**Pull request merged**
